USE [RI_Prospects]
GO

/****** Object:  Table [dbo].[Prospects_Followup]    Script Date: 04/19/2012 12:51:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Prospects_Followup](
	[fuID] [int] IDENTITY(1,1) NOT NULL,
	[cID] [int] NOT NULL,
 CONSTRAINT [PK_Prospects_Followup] PRIMARY KEY CLUSTERED 
(
	[fuID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

