USE [RI_Prospects]
GO

/****** Object:  Table [dbo].[Prospects_Months]    Script Date: 04/19/2012 12:53:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Prospects_Months](
	[mID] [int] IDENTITY(1,1) NOT NULL,
	[month] [varchar](50) NOT NULL,
	[sortID] [int] NOT NULL,
 CONSTRAINT [PK_Prospects_Months] PRIMARY KEY CLUSTERED 
(
	[mID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


