USE [RI_Prospects]
GO

/****** Object:  Table [dbo].[Prospects_Premiums]    Script Date: 04/19/2012 12:53:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Prospects_Premiums](
	[premID] [int] IDENTITY(1,1) NOT NULL,
	[premium] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Prospects_Premiums] PRIMARY KEY CLUSTERED 
(
	[premID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


